name: Update & Deploy NSE Buzz Data

on:
  schedule:
    # Every 2 hours during NSE trading hours (9:15–15:30 IST)
    - cron: "15 4-10 * * 1-5"
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate JSON from SerpAPI
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: python scripts/generate_json.py

      - name: FTP Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /public_html/
          dangerous-clean-slate: true
